theme: jekyll-theme-architect

title: [json-processing-spec]
description: []

# sidebar links url
links:
  source: https://github.com/javaee/json-processing-spec
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

